language: node_js
node_js:
- node
deploy:
  provider: heroku
  api_key:
    secure: mUsz8NxUayDoqNX1LSAP3abrzOttH29P0dSJER5wPyGg7HsUsQSuvnnU/43/ERhOzKZ8WvSjGlVIAG3FcXO0+0U/dD4bayTSnJ7tJDDLKRynBAbOxSV7UjWIZL4Siar2crv65PLR+uNeNI4m3ZuV3cUVYaxkxshDK9NVYLJjgLCzufpyB4X7kvK2He9Xr6xB3DdL5ZRkzKqvPHDKZE+XpsFz3dnlvZ9eDwHG4LOOWtYdofFhR8ezMfauRp2DTIUcSJauYBec/sUQAFF0WtdgS4jKpyDV8Aa4vVi/wPm8WRkFHnZyySlLYS3wR279WI6yCEKLpvsgi8GozNRZIuox7T7MpKF4Z9Uv62dVLlH1Mvl1eF1TGJjOlCaWgeSoaEES2UEigb5emX4dqXcFmZ3bCFPmTTxf3sivgk8i2Bvqsvz9vz3r+kgfNvF5BuhSBa6802WVu+Bi81j9uYBEkbm6gZvpH+UH1czPtujhr85yifi7imiOZiyrR3pM+ZeIGfYh/pjd2SbmuP44AT7W6p551acPec96XOyec6VYEYKu8fNQp6zZWhp3EUTSXXNz40Tb6HYP+bgolPHravTw+hJg6cTpPnGexKruR72+BC0pY5lBOneCKTdaJWzyFH0kE2BIjUrYyXXUktEJtjEVoXGbpRxRTWk/YDTZBxUxAABZv4o=
