language: node_js
node_js:
- node
deploy:
  provider: heroku
  api_key:
    secure: "aqmFxK2Pl0NkDE3ImEaCNJr7dwFrfGdrLJDonigdNOfGaR0Ypj0l+aApR39XnWt/JBXsBwGrEKVif6u7jREGAM+IfQ1LJFWkD/a96opbMrlJjKv8d0VNV2kPtvn+6sz1+TrK6FncauYMbpK73CDcZMO4n2iN5VCXvOGbq+HDjxP912tq5YJ0Qpa3kOAikEywGTRbRnGkAUgqAszkkV8Dt6JPPAHz+M5sHJoKjf14SbE+qVSGpm9rWooGDVpu6Lx+dTnDGsEBl4Zt2DmthteUTWzMfYdxyMGUXv4QbVr3wksreU74Xudaw3eVY17Urgac6dZZmcuev/TjPpkoku5wWWdvP8cHUunK//0ZNoKzb9jwO89QneS8jJAme5yz5aELfRPtwDoMAwe0o25yBe0Ibjej5Qr8hKwjf4DzXR0JtvUJbj0L7ehhrA2wg8gqnLOtd1aNJ4UpHPzuZ5G9BG31lwjCCY8dk7QwgxzMBsXuQnos9cVZcR6ix3cT6oC6mHAQeQ9RbRbBrvLRVDh8qIphT9aNxxR/g+LL/+TNxQFMOSzKyv7/M2wyi8Qm+uG7X7WFVTZKBSQgUnuj2/TjDAbEU8wE2rgy69AvGqtXS22e4VHJlkIJtHJJDerxRCqzuE3rlUgV2Qu286kn/5heTet8LlfiXObhq0rrxk+FTe1FMMc="
