language: node_js
node_js:
- node
deploy:
  provider: heroku
  api_key:
    secure: "rwwQzn9cnSJqv9+EElrZKuE6zb4Z3QR5SptQlzwW3wAlj4mfx9BD9l09ODX2aBgUjfaV8TVSL/Sb6qURIN3klEWPoYkNMRWq4A8DRa6XW01sd4q9g2EZMxo8PbHLMl3+MWP024DCLwPoLw1jnKL+maW915/d/J889V0ptNa1Xpoq9XmNfZJT/1AuqlWJqFlYNXLM9pIQskiF6d86UR9ESuRh+wm7F0BiR/2VBYh3QDwszA80LU1Lm+H9ln4GVBgG/VBVJUxDWLJAI3xxmHIW9+sCBjJMP5wYQDZJo6SSG3lZYJRIPGhua7lckusOwzB1ogAnVayyDTFOIEyLndX58fXMAp53RLLeRcV4ofgFSbfh+NimCcT2I8oGHVlqT62laV3rMRZWIrV+kN61Jjx01iyjJ6OpFDarDJ30HuBXWzHxmSZVOXS2nLkofykMEwAxPRn9qc5uCX65fhUGLNEdbXCZo7wOtHP34odkS1xZfl8F4jSdcSkJGPoKORR/b/Wz+7syTTMjl68GJSv8BPccZReMu8QRXx1BXZHZns8aLOzrwuDaL7u6TYq0TtTuP2DRMbXUTBNJblc8PHY7QYuAjNzith7cOsqPzzepkHozCaxvMXMmOVMsYpXVZmUo+iGoAHcxXgCW1LSdLnxwCSN2pJKBkoRY+AGxN76mnCLkZ30="