language: node_js
node_js:
- node
deploy:
  api_key:
    secure: WKm2uWFyVT2Zj4BE2Hi22my7/Cb/RMC4076V7JFrBufUtZDKORIwimFy0zN2hbonN4fo3AvPxo1PEUApu0XBAngkDTDZp8nqp+ia8v7LqQY17OFgm5kaTGXj5jzJQ9apgobN66Dwuqmrj/aacYCbAzkEgMsT+m7Sm4fLc3N5uR2ER8oeDEoBZuFzq/Bl3WStTGq3uZTLTONHicZusNN/x/ttTj8M0FPJTBNmJXq6iVOr3HYGZJMgSi3wYXER1XF/yABbpqLqxLVynUBWzUz71Ac/+JzxszlzkyMpUv8yXhCQKop065f60fANqt9t/eOlFXb1TvEsfzSisu8NOzKB2E0MVEgu2Xd0vsei7YhFZ4jl3E3DkkiNv6Dg80aeWdrVyyxWuU+4Fuh0tlmQty8IwdpjHKT+i0xDXQX+DjwiaHR3mmMLbS2hXKG+B490kjy+2EQ+NsPoi5NLppUfM/S7SuL9LB7AL7X4vhe0QBVN9CGPd3M+rJtMnVvJD2hVidmeBtCnSyzWOTnbtmaQ1JgSZeUbknB2Gs6HGYJrMfjyFhRwEvizYOkcDzH8sEhD5ElLPInZqzGolUZ6WLWGhpVebr3Sq5AYanDKMALV5x8BiM48DpVA48DXZ4cCUwnz4NGnrQt3V+fmLt8VOF5g6fprX2qCqvbveY+N79FZ8pDQhI0=
