language: node_js
node_js:
- node
deploy:
  api_key:
    secure: EFaYMIMmMyyZK0NZyZLObdRUhMjy39ojaXUwtBAdKMinBtBwfvasOAt7uZ0ljCVDF95nXAxc2fcYa4d6S+oKWjizNtL/CFgftDuZDuXC89kWTwSRdSpnSFm6/2igRgzS+CZAcqc5BiZfF4Zr6IJBe/28yY9za1PvBGQCgXFmpyvlI36BKxeNSgdhPJRngmh9z94WmMI+cLrcDtYnxN0fSCmlFhmh0oJXIuR1nU8kLVN/RzS7HrDUOwwzDeRbaLYBLVhmvfGBz7HcI+nQubaSJ/wgcCq4FmuxwHRWIe2dcwhbPSYM7M3tRQFym85TYQ3YmgJ5Ckhf6L0keP7J7W71Yw2ju25Ad9EYt22F0gMRqNfiFIQuMrh2gGHxSAAXLrmdrvZskRTb+p1u0OhUnMMeySY0g5HAELGjOv6YBF9qkq+gnVOhEHespsBFp6zUgMpwOE2glsruDU7yJX6nWiWjxApv/Kb1od6QUIXtZWLpMj+d9jCvhtSDAVF4wlcXWK2bOpsESDT8BeWRkIet0Wud/LgUwcEr4B+z7JosjfpkMuEXlG/1mVOwASmpt7Jyk8dG3jVebrhPYTSxXHgHjlhsm6aJU7oceuayJ8p3GTYlPf+mp9WoGbVBBN6uqYXMvn5Ae54cLiV+eLvq/qtoCFtOV4W/AS+wpxX4D5V/QSLjKIU=
