language: node_js
node_js:
- node
deploy:
  api_key:
    secure: "VjZNKj09K25ooYD2bqOE7whAOiKOG/81GXAbcpEOT+up0Kllc7E4k+BlQaO1fTEuCpvkM3LqiogBw6cFlkaM0gLaZyJxQayZBjKa3AC5gEy5tKEtHzud9ESJ1H3UWyhnQX+iRTvTi6XJLAUGNrMuYP57YtqKJUhwQDUIDekRb5lF/yse/GtT/HtP+aTurNRErt5J8CXa7k9y4j5T6+G1jZuf27XU3xXmyqzKSN2VsbU137oLvlEfk9kEKYWsvkABREJgxbNdDmPtGRXM03oP1mh3nk6n7UF9BpsFk50RFB0osy3+g1Ro5vLd8xL59X3egnsyGSa1CTq8qANXXceS5JKdsXFlG8LUBjM3kfkawLwQl2ZL/O37u9C/nqCsgGT4gt5fdNJulJQJtPA2TlMPinRNyoTg7WpGNwT8L9VqNS61uN3A6KLont0O32kPGYPtTpqeKL6P6JWyhcgpVU3DBiwuw5kNAVJqNd12j0QdIxtsco6fyuF8KPVdRvAD8VIdByCZN+wmP1vx4TQfIoP56LVVHmEd56dBiBOUlg8YhYM3mEFALO5MceQKyWt5b1tqWGqWpZt6uGbjx0konLx3JiE6dQJgOniU/WxswRjusclZyhL6Au6m+vF92ggar6nH8CC8y54rGQkiyZgvLFK5VJ6SB1Paqs/T8Myf2Zc9FvY="
